Program To understand the conditions of the computer, we have some special keywords.
If
IF ELSE
IF ELIF ELSE
NESTED IF

In [2]:
if True: # indentiation is always 4 spaces
    print('Data Science')

Data Science


In [4]:
if False:
    print('Data Science')
print('bye for now')

bye for now


In [8]:
if True: # indentiation is always 4 spaces - both print will be output.
    print('Data Science')
print('bye for now')

Data Science
bye for now


Lets do one program as if number divide by 2 then reminder is 0 then it is even number, if reminder is not 0 then it is odd number.

In [11]:
#to print only even number

x = 14
r = x % 2 

if r == 0:
    print('Even number')

if r == 1:
    print('Odd Number')

Even number


In [25]:
#to print only even number

x = 14
r = x % 2 

if r == 0:
    print('Even number')
else:
    print('Odd Number')

Even number


In [27]:
#to print only even number
x = 11
r = x % 2 

if r == 0:
    print('Even number')    

In [17]:
x = 5
r = x % 2 

if r == 0:
    print('Even number')
print('odd number')

odd number


In [29]:
x = 8 #both print will be output
r = x % 2 

if r == 0:
    print('Even number')
print('odd number')

Even number
odd number


In [21]:
x = 8
r = x % 2 

if r == 0:
    print('Even number')
if r == 1:
    print('odd number')

Even number


In [23]:
x = 7
r = x % 2 

if r == 0:
    print('Even number')
if r == 1:
    print('odd number')

odd number


In [31]:
x = 13
r = x % 2 

if r == 0:
    print('Even number')
    
if r != 0:
    print('odd number')

odd number


if we observe the code its too many line cuz many of the coder always they wanted to reduce the code lenght which is very good practise. instead of 2 if we can use if-- else 

In [34]:
x = 2
r = x % 2

if r == 0:
    print( ' Even number')
else:
    print('Odd Number')

 Even number


In [36]:
x = 3
r = x % 2

if r == 0:
    print('Even number')
    if x>5:
        print('greater number')
else:
    print('Odd Number')

Odd Number


In [38]:
x = 4
r = x % 2

if r == 0:
    print('Even number')
    if x>5:
        print('greater number')
else:
    print('Odd Number')

Even number


NESTED IF (if we have 2 condition so we need to implment with nested if )

In [41]:
x = 6
r = x % 2
if r == 0:
    print('Even number')
    if x>5:
        print('greater number')
    else:
        print('not greater')
else:
    print('Odd Number')    

Even number
greater number


In [43]:
x = 2
r = x % 2

if r == 0:
    print('Even number')
    if x>5:
        print('greater number')
    else:
        print('not greater')
else:
    print('Odd Number')  

Even number
not greater


We do have concept of ( IF - ELIF- ELSE) 
e.g i want to print ( 1--> one , 2 --> two, 3--> three, 4--> four, 5- five)

In [46]:
#when you use if it will check all condition but if we mention as elif then it wont check all condition
x = 1

if(x == 1):
    print('one')
if(x == 2):
    print('Two')
if(x == 3):
    print('Three')
if(x == 4):
    print('four')

one


In [48]:
x = 2

if(x == 1):
    print('one')
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('four')

Two


In [50]:
x = 5

if(x == 1):
    print('one')
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('four')

In [52]:
x = 5

if(x == 1):
    print('one')
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('four')
else:
    print('wrong output')


wrong output


In [54]:
x = 15

if(x == 1):
    print('one')
elif(x == 2):
    print('Two')
elif(x == 3):
    print('Three')
elif(x == 4):
    print('four')
   
else:
    print('wrong output')

wrong output


In [56]:
print('data science')

data science


LOOPS -- in programing world some time we keep on repeating , may be you want to repeat 5 statement so one way is copy & paste multiple times or other way is. if you want to print the datascience 10 times then what you will you cant copy for 10 times , if you want to print 1000 times then you cant do manualy . 
that is the reason why we need to apply loop ->
2 type of loops --  While loop & For loop

In [59]:
i = 1          # initializing
while i<=5:    # condition
    print('data science')
    i = i + 1  # increment

data science
data science
data science
data science
data science


In [61]:
i = 5          # initializing
while i>=1:    # condition
    print('data science')
    i = i - 1  # decrement

data science
data science
data science
data science
data science


In [63]:
i = 1          # initializing
while i<=5:    # condition
    print('data science',':',i)
    i = i + 1  # increment

data science : 1
data science : 2
data science : 3
data science : 4
data science : 5


In [65]:
i = 5          # initializing
while i>=1:    # condition
    print('data science',':',i)
    i = i - 1  # decrement

data science : 5
data science : 4
data science : 3
data science : 2
data science : 1


can we use multiple while loop || nested while loop 
to understand nested whild indepth understand you can use pycharm debug with f8 option

In [72]:
i = 1

while i<=5:
    print(' data science') # when we mention end then new line will not create
    j = 1
    while j<=4:
        print(' technology')
        j = j + 1
        
    i = i + 1
    print()

 data science
 technology
 technology
 technology
 technology

 data science
 technology
 technology
 technology
 technology

 data science
 technology
 technology
 technology
 technology

 data science
 technology
 technology
 technology
 technology

 data science
 technology
 technology
 technology
 technology



In [74]:
i = 1
while i<=5:
    print(' data science', end = "") # when we mention end then new line will not create
    j = 1
    while j<=4:
        print(' technology', end="")
        j = j + 1
        
    i = i + 1
    print()

 data science technology technology technology technology
 data science technology technology technology technology
 data science technology technology technology technology
 data science technology technology technology technology
 data science technology technology technology technology


In [76]:
i = 1
while i<=5:
    print(' data science', end = "  *") # when we mention end then new line will not create
    j = 1
    while j<=4:
        print(' technology', end="  *")
        j = j + 1
        
    i = i + 1
    print()

 data science  * technology  * technology  * technology  * technology  *
 data science  * technology  * technology  * technology  * technology  *
 data science  * technology  * technology  * technology  * technology  *
 data science  * technology  * technology  * technology  * technology  *
 data science  * technology  * technology  * technology  * technology  *


In [78]:
i = 1
while i <= 4 :
    j = 0
    while  j <= 3 :
        print(i*j, end=" ")
        j += 1
    print()
    i += 1

0 1 2 3 
0 2 4 6 
0 3 6 9 
0 4 8 12 


FOR LOOP  -
normally while loop it work with condition but for loop it will work with sequence (list, string,int)


In [81]:
name = 'nit'
for i in name:
    print(i)

n
i
t


In [83]:
name1 = [1,3.5,'hallo']

for i in name1:
    print(i)

1
3.5
hallo


In [85]:
for i in [2, 3, 7.8, 'hi']:
    print(i)

2
3
7.8
hi


In [87]:
for i in range(5):
    print(i)

0
1
2
3
4


In [89]:
for i in range(1,5):
    print(i)

1
2
3
4


In [91]:
for i in range(1,10,3):
    print(i)

1
4
7


In [93]:
# print the numer which is not divisible by 5

for i in range(1,11):
    
    if i%5 != 0 :
      print(i)

1
2
3
4
6
7
8
9


In [99]:
# can you write the python code for 5 multiplication table 

for i in range(1,51):
    
    if i%5 == 0:
      print(i)

5
10
15
20
25
30
35
40
45
50


# LETS DISCUSS ABOUT 3 KEYWORDS -- BREAK || CONTINUE || PASS
BREAK STATEMNT - if you apply break statment in a loop then it will end the loop
# Pass = skips block of code( function, class etc)
# Continue= skips 1 step/iteration during loop 
# Break= jumps out of the function/loop

In [102]:
for i in range(1,11):
    print(i)    

1
2
3
4
5
6
7
8
9
10


In [106]:
for i in range(1,11):
    if i == 5:
        break #==> WHILE YOU WORK WITH COMPUTER VISION PROJECT 

In [108]:
for i in range(1,11):
    if i == 5:
        break #==> WHILE YOU WORK WITH COMPUTER VISION PROJECT 
    print(i)

1
2
3
4


In [110]:
for i in range(1,11):
    if i == 5:
        break #==> WHILE YOU WORK WITH COMPUTER VISION PROJECT 
print(i)

5


# in continue ,  loop wont be terminate

In [113]:
for i in range(1,11):
    if i == 5:
        continue 
    print(i)

1
2
3
4
6
7
8
9
10


In [115]:
for i in range(1,11):
    if i == 5:
        continue 
    print('hello ',i)   

hello  1
hello  2
hello  3
hello  4
hello  6
hello  7
hello  8
hello  9
hello  10


#PASS Statement - pass the code & it wont go

In [120]:
for i in range(1,11):  
    pass

# PRINTING PATTERN IN PYTHON

In [123]:
print('# # # #')
print('# # # #')
print('# # # #')
print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [125]:
for j in range(4):
    print('#', end="  ")  

#  #  #  #  

In [127]:
for j in range(4):
    print('#', end="  ")
    
for j in range(4):
    print('#', end="  ")

#  #  #  #  #  #  #  #  

In [129]:
for j in range(4):
    print('#', end="  ")
    
print()

for j in range(4):
    print('#', end="  ")

#  #  #  #  
#  #  #  #  

In [131]:
for j in range(4):
    print('#', end="  ")
    
print()

for j in range(4):
    print('#', end="  ")

print()

for j in range(4):
    print('#', end="  ")
    
print()

for j in range(4):
    print('#', end="  ")

#  #  #  #  
#  #  #  #  
#  #  #  #  
#  #  #  #  

In [133]:
for i in range(4):
    for j in range(4):
        print('#', end="  ")
    print()
    # pease use debug mode

#  #  #  #  
#  #  #  #  
#  #  #  #  
#  #  #  #  


In [135]:
for i in range(5):
    for j in range(i):
        print('#', end="  ")
    print()


#  
#  #  
#  #  #  
#  #  #  #  


In [137]:
for i in range(4):
    for j in range(i+1):
        print('#', end="  ")
    print()

#  
#  #  
#  #  #  
#  #  #  #  


In [139]:
for i in range(4):
    for j in range(4-i):
        print('*', end="  ")
    print()

*  *  *  *  
*  *  *  
*  *  
*  


In [141]:
for i in range(4):
    for j in range(4-i):
        print('#', end="  ")
    print()

#  #  #  #  
#  #  #  
#  #  
#  


# For|Else in python
in other language for else not supportable but in python it is supportable
eg- lets print the number from 1- 20 & we dont want print number which is divisible by 5

In [144]:
nums = [12,15,18,21,26]

for num in nums:
    if num % 5 == 0:
        print(num) 

15


In [146]:
nums = [12,14,18,21,25]
for num in nums:
    if num % 5 == 0:
        print(num)  

25


In [148]:
nums = [12,14,18,21,25,20]
for num in nums:
    if num % 5 == 0:
        print(num)  

25
20


In [150]:
nums = [12,14,18,21,25,20]
for num in nums:
    if num % 5 == 0:
        print(num)  
        break

25


In [152]:
nums = [10,14,18,21,20,25]
for num in nums:
    if num % 5 == 0:
        print(num)  
        break #it will print only 1 number then it break  

10


In [156]:
nums = [7,14,18,21,23,27] #hear there is no number which is divisible by 5 we got output as blank
for num in nums:
    if num % 5 == 0:
        print(num)  
       # break

In [158]:
nums = [7,14,18,21,23,27,22] #hear there is no number which is divisible by 5 we got output as blank
for num in nums:
    if num % 5 == 0:
        print(num)  
        break
    else:
        print('Number Not Found') #every iteration it cheking condition

Number Not Found
Number Not Found
Number Not Found
Number Not Found
Number Not Found
Number Not Found
Number Not Found


In [160]:
nums = [7,14,18,21,23,27] #hear there is no number which is divisible by 5 we got output as blank
for num in nums:
    if num % 5 == 0:
        print(num)  
        #break
else:
        print('Not Found') # hear else we dont write in if block but we can write in for block only

Not Found


In [162]:
nums = [10,14,18,21,20,27] #hear there is no number which is divisible by 5 we got output as blank
for num in nums:
    if num % 5 == 0:
        print(num)  
        #break
else:
        print('Not Found')

10
20
Not Found


In [164]:
nums = [10,14,18,21,20,27] #hear there is no number which is divisible by 5 we got output as blank
for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Not Found')

10


# prime number - how to check given number is prime number or not

In [167]:
num = 12

for i in range(2,num):
    if num % i == 0:
        print('Not prime Number')
        break
else:
    print('Prime Number')

Not prime Number


In [169]:
num = 13

for i in range(2,num):
    if num % i == 0:
        print('Not prime Number')
        break
else:
    print('Prime Number')

Prime Number


In [171]:
from array import * 

arr = array('i',[])

n = int(input('Enter the length of the array'))

for i in range(5):
    x = int(input('Enter the next value'))
    arr.append(x)
    print(arr)

Enter the length of the array 5
Enter the next value 2


array('i', [2])


Enter the next value 4


array('i', [2, 4])


Enter the next value 5


array('i', [2, 4, 5])


Enter the next value 6


array('i', [2, 4, 5, 6])


Enter the next value 7


array('i', [2, 4, 5, 6, 7])


# Way of creating array using numpy

In [174]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [176]:
print(arr.dtype)

int32


In [178]:
arr = array([1,2,3,4,5.9])
print(arr)

[1.  2.  3.  4.  5.9]


In [180]:
print(arr.dtype)

float64


In [182]:
arr2 = array([1,2,3,4,5.9],float)
arr2

array([1. , 2. , 3. , 4. , 5.9])

In [184]:
arr3 = array([1,2,3,4,5.6],int)
arr3

array([1, 2, 3, 4, 5])

In [186]:
import numpy as np

In [188]:
arr4 = np.linspace(0, 16, 10) # break the code between 10 spaces between 0 to 16 but why decimal becuase we break into parts thats why it is floats
arr4

array([ 0.        ,  1.77777778,  3.55555556,  5.33333333,  7.11111111,
        8.88888889, 10.66666667, 12.44444444, 14.22222222, 16.        ])

In [190]:
arr5 = np.arange(0,10,2) # arange - as range
arr5

array([0, 2, 4, 6, 8])

In [192]:
arr6 = np.zeros(5)
arr6

array([0., 0., 0., 0., 0.])

In [194]:
arr7 = np.ones(5)
arr7

array([1., 1., 1., 1., 1.])